/**
 * The complete endpoint surface this store is built on — transcribed from the
 * request capture. `impl` describes how this build serves each row:
 *  - "live":    served by the in-app REST gateway with real data
 *  - "session": gateway route exists; requires a signed-in session (the web
 *               app performs it through the Convex client)
 *  - "ui":      a page route; `appRoute` maps it to its equivalent in this app
 *  - "none":    out of scope for this build
 */

export type HttpMethod = "GET" | "POST" | "DELETE";

export type ApiEndpoint = {
  id: number;
  endpoint: string; // display path from the capture
  method: HttpMethod;
  url: string; // original spec URL
  category: string;
  purpose: string;
  statusCode: string;
  calls: number;
  priority: "High" | "Medium" | "Low";
  captured: boolean;
  impl: "live" | "session" | "ui" | "none";
  /** Callable path on the in-app gateway (query strings from the spec omitted). */
  livePath?: string;
  /** For "ui" rows: the equivalent route in this app. */
  appRoute?: string;
  /** Sample body used by the API reference "Try it" tester. */
  sampleBody?: Record<string, unknown>;
  note?: string;
};

export const API_ENDPOINTS: ApiEndpoint[] = [
  // ---- captured ----
  {
    id: 1,
    endpoint: "/api/6/user/signup/status",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/6/user/signup/status",
    category: "Auth",
    purpose: "Check if user exists",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "live",
    livePath: "/api/6/user/signup/status",
    sampleBody: { email: "buyer@example.com" },
  },
  {
    id: 2,
    endpoint: "/api/7/user/otp/generate",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/7/user/otp/generate",
    category: "Auth",
    purpose: "Generate OTP for login",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "live",
    livePath: "/api/7/user/otp/generate",
    sampleBody: { email: "buyer@example.com" },
    note: "OTP delivery is handled by the built-in email OTP provider — see /auth.",
  },
  {
    id: 3,
    endpoint: "/api/1/user/login/otp",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/user/login/otp",
    category: "Auth",
    purpose: "Verify OTP and login",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "live",
    livePath: "/api/1/user/login/otp",
    sampleBody: { email: "buyer@example.com", otp: "000000" },
    note: "Verify the code on /auth — the email OTP provider signs you in.",
  },
  {
    id: 4,
    endpoint: "/api/1/user/session-identity",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/user/session-identity",
    category: "Auth",
    purpose: "Validate session",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "session",
    livePath: "/api/1/user/session-identity",
  },
  {
    id: 5,
    endpoint: "/4/user/state",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/4/user/state",
    category: "User",
    purpose: "Get user profile",
    statusCode: "200",
    calls: 4,
    priority: "High",
    captured: true,
    impl: "session",
    livePath: "/4/user/state",
  },
  {
    id: 6,
    endpoint: "/api/1/location/serviceability",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/location/serviceability",
    category: "Location",
    purpose: "Check delivery availability",
    statusCode: "200",
    calls: 4,
    priority: "High",
    captured: true,
    impl: "session",
    livePath: "/api/1/location/serviceability",
    sampleBody: { pincode: "560001" },
  },
  {
    id: 7,
    endpoint: "/api/4/location/update",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/4/location/update",
    category: "Location",
    purpose: "Update delivery address",
    statusCode: "200",
    calls: 2,
    priority: "High",
    captured: true,
    impl: "session",
    livePath: "/api/4/location/update",
    sampleBody: { pincode: "560001", city: "Bengaluru" },
  },
  {
    id: 8,
    endpoint: "/api/1/contacts",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/contacts?source=entry",
    category: "Location",
    purpose: "Get saved addresses",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "session",
    livePath: "/api/1/contacts",
  },
  {
    id: 9,
    endpoint: "/api/3/user/contact",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/3/user/contact?marketplace=HYPERLOCAL",
    category: "Location",
    purpose: "Get Hyperlocal contact",
    statusCode: "200",
    calls: 1,
    priority: "Medium",
    captured: true,
    impl: "session",
    livePath: "/api/3/user/contact",
  },
  {
    id: 10,
    endpoint: "/api/5/cart/browse",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/5/cart/browse",
    category: "Cart",
    purpose: "Fetch shopping cart",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "session",
    livePath: "/api/5/cart/browse",
  },
  {
    id: 11,
    endpoint: "/api/5/self-serve/orders",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/5/self-serve/orders/?page=1&filterType=PREORDER_UNITS",
    category: "Orders",
    purpose: "Get order history",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "session",
    livePath: "/api/5/self-serve/orders",
  },
  {
    id: 12,
    endpoint: "/api/2/wallet/balance",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/2/wallet/balance",
    category: "Payment",
    purpose: "Get wallet balance",
    statusCode: "200",
    calls: 2,
    priority: "Medium",
    captured: true,
    impl: "session",
    livePath: "/api/2/wallet/balance",
  },
  {
    id: 13,
    endpoint: "/api/2/wallet/egv/active",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/2/wallet/egv/active",
    category: "Payment",
    purpose: "Get active vouchers",
    statusCode: "200",
    calls: 1,
    priority: "Medium",
    captured: true,
    impl: "session",
    livePath: "/api/2/wallet/egv/active",
  },
  {
    id: 14,
    endpoint: "/api/1/affordability/bnpl/account",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/affordability/bnpl/account",
    category: "Payment",
    purpose: "Check BNPL eligibility",
    statusCode: "200",
    calls: 1,
    priority: "Medium",
    captured: true,
    impl: "live",
    livePath: "/api/1/affordability/bnpl/account",
    sampleBody: {},
    note: "Demo response — BNPL is not enabled at checkout.",
  },
  {
    id: 15,
    endpoint: "/api/1/egv/denominations",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/egv/denominations",
    category: "Voucher",
    purpose: "Get gift card amounts",
    statusCode: "200",
    calls: 2,
    priority: "Low",
    captured: true,
    impl: "live",
    livePath: "/api/1/egv/denominations",
  },
  {
    id: 16,
    endpoint: "/api/1/egv/locations",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/egv/locations",
    category: "Voucher",
    purpose: "Get redemption locations",
    statusCode: "200",
    calls: 2,
    priority: "Low",
    captured: true,
    impl: "live",
    livePath: "/api/1/egv/locations",
    note: "Static demo list of redemption points.",
  },
  {
    id: 17,
    endpoint: "/api/4/page/fetch",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/4/page/fetch?cacheFirst=false",
    category: "Content",
    purpose: "Fetch page content",
    statusCode: "200",
    calls: 16,
    priority: "High",
    captured: true,
    impl: "live",
    livePath: "/api/4/page/fetch",
  },
  {
    id: 18,
    endpoint: "/api/1/action/view",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/action/view",
    category: "Analytics",
    purpose: "Track user actions",
    statusCode: "200",
    calls: 9,
    priority: "Medium",
    captured: true,
    impl: "live",
    livePath: "/api/1/action/view",
    note: "Demo — events are acknowledged, not persisted.",
  },
  {
    id: 19,
    endpoint: "/api/1/connekt/push/callback",
    method: "POST",
    url: "https://www.flipkart.com/api/1/connekt/push/callback",
    category: "Notification",
    purpose: "Push notification callback",
    statusCode: "200",
    calls: 1,
    priority: "Low",
    captured: true,
    impl: "live",
    livePath: "/api/1/connekt/push/callback",
    sampleBody: { event: "delivered", token: "demo-device" },
  },
  {
    id: 20,
    endpoint: "/",
    method: "GET",
    url: "https://www.flipkart.com/",
    category: "UI",
    purpose: "Homepage",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "ui",
    appRoute: "/",
  },
  {
    id: 21,
    endpoint: "/account/login",
    method: "GET",
    url: "https://www.flipkart.com/account/login?ret=/",
    category: "UI",
    purpose: "Login page",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "ui",
    appRoute: "/auth",
  },
  {
    id: 22,
    endpoint: "/account",
    method: "GET",
    url: "https://www.flipkart.com/account/?rd=0&link=home_account",
    category: "UI",
    purpose: "Account page",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "ui",
    appRoute: "/account",
  },
  {
    id: 23,
    endpoint: "/chat",
    method: "GET",
    url: "https://www.flipkart.com/chat/3?chatType=EHC&contextId=OD438370803786048500",
    category: "UI",
    purpose: "Customer support",
    statusCode: "200",
    calls: 1,
    priority: "Low",
    captured: true,
    impl: "ui",
    note: "Not built — support chat is out of scope.",
  },
  {
    id: 24,
    endpoint: "/flipkart-minutes-store",
    method: "GET",
    url: "https://www.flipkart.com/flipkart-minutes-store?marketplace=HYPERLOCAL",
    category: "UI",
    purpose: "Quick commerce",
    statusCode: "200",
    calls: 1,
    priority: "Medium",
    captured: true,
    impl: "ui",
    note: "Not built — the Hyperlocal storefront is out of scope.",
  },
  {
    id: 25,
    endpoint: "/payments/preload",
    method: "GET",
    url: "https://www.flipkart.com/payments/preload?url=https://www.flipkart.com/payments",
    category: "UI",
    purpose: "Payment preload",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "ui",
    appRoute: "/checkout",
    note: "Handled inside checkout.",
  },
  {
    id: 26,
    endpoint: "/payments",
    method: "GET",
    url: "https://www.flipkart.com/payments?isRevampedDesktopView=true&token=...",
    category: "UI",
    purpose: "Payment page",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "ui",
    appRoute: "/checkout",
  },
  {
    id: 27,
    endpoint: "/viewcheckout",
    method: "GET",
    url: "https://www.flipkart.com/viewcheckout?view=HYPERLOCAL&marketplace=HYPERLOCAL&tr_tenant=HYPERLOCAL",
    category: "UI",
    purpose: "Checkout page",
    statusCode: "200",
    calls: 1,
    priority: "High",
    captured: true,
    impl: "ui",
    appRoute: "/checkout",
  },
  {
    id: 28,
    endpoint: "Google Ads Tracking",
    method: "GET",
    url: "https://googleads.g.doubleclick.net/pagead/...",
    category: "Tracking",
    purpose: "Google conversion tracking",
    statusCode: "200",
    calls: 1,
    priority: "Low",
    captured: true,
    impl: "none",
    note: "External third-party tag — not part of this build.",
  },
  {
    id: 29,
    endpoint: "Google Ads Tracking",
    method: "GET",
    url: "https://googleads.g.doubleclick.net/pagead/...",
    category: "Tracking",
    purpose: "Google conversion tracking",
    statusCode: "200",
    calls: 1,
    priority: "Low",
    captured: true,
    impl: "none",
    note: "External third-party tag — not part of this build.",
  },

  // ---- missing from capture, implemented here ----
  {
    id: 101,
    endpoint: "/api/v2/search",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/v2/search",
    category: "Search",
    purpose: "Product search",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "live",
    livePath: "/api/v2/search",
    note: "Supports ?q=, ?category=, ?sort=price-asc|price-desc|rating|newest|featured.",
  },
  {
    id: 102,
    endpoint: "/api/1/product/{id}",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/product/{id}",
    category: "Product",
    purpose: "Get product details",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "live",
    livePath: "/api/1/product/{id}",
  },
  {
    id: 103,
    endpoint: "/api/5/cart/add",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/5/cart/add",
    category: "Cart",
    purpose: "Add item to cart",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "session",
    livePath: "/api/5/cart/add",
    sampleBody: { productId: "{id}", quantity: 1 },
  },
  {
    id: 104,
    endpoint: "/api/5/cart/remove",
    method: "DELETE",
    url: "https://2.rome.api.flipkart.com/api/5/cart/remove",
    category: "Cart",
    purpose: "Remove item from cart",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "session",
    livePath: "/api/5/cart/remove",
    sampleBody: { productId: "{id}" },
  },
  {
    id: 105,
    endpoint: "/api/1/orders/place",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/orders/place",
    category: "Orders",
    purpose: "Place order",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "session",
    livePath: "/api/1/orders/place",
    sampleBody: { addressId: "", paymentMethod: "wallet" },
  },
  {
    id: 106,
    endpoint: "/api/2/payment/initiate",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/2/payment/initiate",
    category: "Payment",
    purpose: "Initiate payment",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "session",
    livePath: "/api/2/payment/initiate",
    sampleBody: { orderId: "", method: "wallet" },
  },
  {
    id: 107,
    endpoint: "/api/1/coupon/validate",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/coupon/validate",
    category: "Discount",
    purpose: "Validate coupon code",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "live",
    livePath: "/api/1/coupon/validate",
    sampleBody: { code: "STAPLE10" },
    note: "Demo codes: STAPLE10 (10% off), FREESHIP (free delivery).",
  },
  {
    id: 108,
    endpoint: "/api/1/product/{id}/reviews",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/product/{id}/reviews",
    category: "Reviews",
    purpose: "Get product reviews",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "live",
    livePath: "/api/1/product/{id}/reviews",
  },
  {
    id: 109,
    endpoint: "/api/1/wishlist",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/wishlist",
    category: "Wishlist",
    purpose: "Get wishlist items",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "session",
    livePath: "/api/1/wishlist",
  },
  {
    id: 110,
    endpoint: "/api/1/wishlist/add",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/wishlist/add",
    category: "Wishlist",
    purpose: "Add to wishlist",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "session",
    livePath: "/api/1/wishlist/add",
    sampleBody: { productId: "{id}" },
  },
  {
    id: 111,
    endpoint: "/api/1/categories",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/categories",
    category: "Browse",
    purpose: "Get categories",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "live",
    livePath: "/api/1/categories",
  },
  {
    id: 112,
    endpoint: "/api/1/browse/departments",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/browse/departments",
    category: "Browse",
    purpose: "Get departments",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "live",
    livePath: "/api/1/browse/departments",
    note: "Alias of /api/1/categories in this build.",
  },
  {
    id: 113,
    endpoint: "/api/1/deals",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/deals",
    category: "Deals",
    purpose: "Get ongoing deals",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "live",
    livePath: "/api/1/deals",
  },
  {
    id: 114,
    endpoint: "/api/1/offers",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/offers",
    category: "Offers",
    purpose: "Get promotions",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "live",
    livePath: "/api/1/offers",
  },
  {
    id: 115,
    endpoint: "/api/1/seller/{id}",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/seller/{id}",
    category: "Seller",
    purpose: "Get seller info",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "none",
    note: "Out of scope — every product is sold by Staple directly.",
  },
  {
    id: 116,
    endpoint: "/api/1/product/{id}/availability",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/product/{id}/availability",
    category: "Inventory",
    purpose: "Check stock status",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "live",
    livePath: "/api/1/product/{id}/availability",
  },
  {
    id: 117,
    endpoint: "/api/1/orders/{id}/return",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/orders/{id}/return",
    category: "Returns",
    purpose: "Initiate return",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "session",
    livePath: "/api/1/orders/{id}/return",
    sampleBody: { reason: "changed my mind" },
  },
  {
    id: 118,
    endpoint: "/api/1/orders/{id}/tracking",
    method: "GET",
    url: "https://2.rome.api.flipkart.com/api/1/orders/{id}/tracking",
    category: "Tracking",
    purpose: "Get order tracking",
    statusCode: "N/A",
    calls: 0,
    priority: "High",
    captured: false,
    impl: "session",
    livePath: "/api/1/orders/{id}/tracking",
  },
  {
    id: 119,
    endpoint: "/api/1/orders/{id}/cancel",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/orders/{id}/cancel",
    category: "Cancellation",
    purpose: "Cancel order",
    statusCode: "N/A",
    calls: 0,
    priority: "Medium",
    captured: false,
    impl: "session",
    livePath: "/api/1/orders/{id}/cancel",
    sampleBody: {},
  },
  {
    id: 120,
    endpoint: "/api/1/product/{id}/notify-me",
    method: "POST",
    url: "https://2.rome.api.flipkart.com/api/1/product/{id}/notify-me",
    category: "Notifications",
    purpose: "Notify when back in stock",
    statusCode: "N/A",
    calls: 0,
    priority: "Low",
    captured: false,
    impl: "live",
    livePath: "/api/1/product/{id}/notify-me",
    sampleBody: { productId: "{id}" },
    note: "Demo — the request is acknowledged; emails are stubbed.",
  },
];

export const API_CATEGORIES = [
  ...new Set(API_ENDPOINTS.map((e) => e.category)),
].sort();

export const API_STATS = API_ENDPOINTS.reduce(
  (acc, e) => {
    acc.total += 1;
    if (e.captured) acc.captured += 1;
    else acc.missing += 1;
    acc.calls += e.calls;
    if (e.impl === "live") acc.live += 1;
    if (e.impl === "session") acc.session += 1;
    return acc;
  },
  { total: 0, captured: 0, missing: 0, calls: 0, live: 0, session: 0 },
);
